### ISSUE TITLE
feature: allow to launch repairnator on an existing list of buildids 

### ISSUE THREAD

**Issue by surli** [Spirals-Team/librepair#116]
We should upgrade launch_repairnator.sh to allow to pass a list of buildids as an argument: if it exists, then we don't launch the scanner, but only the docker pool on the existing list of buildids.

**Comment by fermadeiral** [comment]
In some way, we already had this (build mode). Do you want the "same thing" but not related to Scanner as before? Maybe a refactoring is required, since we have to create a list of BuildToBeInspected from the build ids file, and we already do this creation also in the Scanner. I mean, I think we should think in a solution to put the code that do this work (list of BuildToBeInspected) in another module and then we use this module in the Scanner and also to do what you want now.

**Comment by surli** [comment]
No we don't need to add anything in the java code to do that. It's simply a small change in the bash file `launch_repairnator.sh` use to run dockerpool. It should only be able to bypass the scanner step, and to replace a variable with the path given in parameter.
